[package]
name = "ecolysis_core"
license = "MIT"
version = "0.0.1"
edition = "2021"
description = "An in-development package for ecological and biological simulation and analysis."

[dependencies]
csv = "1.3.0"
rand = "0.8.5"
statrs = "0.18.0"
